version: "3.8"

services:
  log:
    image: fluent/fluent-bit:3.0.3
    container_name: fluentbit
    command:
      - -c
      - /etc/fluent-bit/fluent-bit.conf
    volumes:
      - ./conf/fluent-bit.conf:/etc/fluent-bit/fluent-bit.conf
      - ./conf/parsers.conf:/etc/fluent-bit/parsers.conf
      - ./logs:/var/logs
  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./conf/local-config.yaml:/etc/loki/local-config.yaml     
  grafana:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m